// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR_Q33bjKEBKtPyTOLRDlfahsFcCbVdCA',
    appId: '1:438390473487:web:eaa86cf4efe23e8733b47a',
    messagingSenderId: '438390473487',
    projectId: 'findmyevent-6a245',
    authDomain: 'findmyevent-6a245.firebaseapp.com',
    storageBucket: 'findmyevent-6a245.appspot.com',
    measurementId: 'G-C1S8HG6S0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_P_YiY1p_I9meoVAQcCpHgjJQKviyfQ',
    appId: '1:438390473487:android:f9dc1a953e95130033b47a',
    messagingSenderId: '438390473487',
    projectId: 'findmyevent-6a245',
    storageBucket: 'findmyevent-6a245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJeS__TeffKa3JGoa4Fblqc6ceZBF-QfE',
    appId: '1:438390473487:ios:87a4e978c170889933b47a',
    messagingSenderId: '438390473487',
    projectId: 'findmyevent-6a245',
    storageBucket: 'findmyevent-6a245.appspot.com',
    iosClientId: '438390473487-d18fv9j0co8ro10u50p9por264j6817m.apps.googleusercontent.com',
    iosBundleId: 'com.example.findmyevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJeS__TeffKa3JGoa4Fblqc6ceZBF-QfE',
    appId: '1:438390473487:ios:87a4e978c170889933b47a',
    messagingSenderId: '438390473487',
    projectId: 'findmyevent-6a245',
    storageBucket: 'findmyevent-6a245.appspot.com',
    iosClientId: '438390473487-d18fv9j0co8ro10u50p9por264j6817m.apps.googleusercontent.com',
    iosBundleId: 'com.example.findmyevent',
  );
}
